### ISSUE TITLE
Optimize `gateway.storage.add` from browser usage

### ISSUE THREAD

**Issue by ggarri** [lightstreams-network/lightstreams-js-sdk#3]
On the usage of a browser, users are going to have a `FilePrototype` Object as a result of a form submit action. On the current implementation, it is required to use a `ReadableStream` which is the object receive once the file is sent to the server.

## What to do
Support usage of `FilePrototype`  for the calls to gateway.storage.add

#### Alternative in meanwhile
```
reader.readAsBinaryString(file)
```
More information [here](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/load_event)

**Comment by EnchanterIO** [comment]
Additional information. As a user I want to pass the following object from the form, that gets streamed in order to avoid reading the whole file to memory using the temporary alternative `readAsBinaryString`

![Uploading Screen Shot 2019-05-16 at 15.22.02.png…]()

**Comment by ggarri** [comment]
Fixed https://github.com/lightstreams-network/lightstreams-js-sdk/commit/3d65806783fea54c09ae48c875d8bfc6ca072922
